name: Deploy on PR Approval

on:
  pull_request_target:
    types:
      - closed

jobs:
   # Se a PR fechada for para a master
  if_merged:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged into the master branch